language: ruby
sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y --no-install-recommends texlive-latex-recommended
  - sudo apt-get install -y --no-install-recommends texlive-latex-extra
  - sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  - sudo apt-get install -y --no-install-recommends make

script:
  - make
  - mkdir -p pdf
  - mv awstream.pdf appendix.pdf pdf/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: pdf
  on:
    branch: master
